uploads = []

[[generated]]
id = "plT-TRWVzqZb7X_VmoDBt"
uri = "file://artifacts/jaire-app/src/assets/the-hub.png"
type = "image"
title = "Modern hot desk in Lagos"

[[generated]]
id = "LZSzxvTs0vlUUifEgAd7C"
uri = "file://artifacts/jaire-app/src/assets/founders-suite.png"
type = "image"
title = "Premium private suite"

[[generated]]
id = "uVFPyENIvnfX93egB5LbO"
uri = "file://artifacts/jaire-app/src/assets/blockchain-lounge.png"
type = "image"
title = "Blockchain lounge area"

[[generated]]
id = "iOzpGPIOR9C8y3NPAehvx"
uri = "file://artifacts/jaire-app/src/assets/board-room.png"
type = "image"
title = "High tech board room"

[[generated]]
id = "ZEwTsIwaUZo2OvusgVzG-"
uri = "file://artifacts/jaire-pitch/public/hero-cover.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "KXsp1Eriud4WsVX7_mp6d"
uri = "file://.local/outputs/JaIre-Workspace--1-.pdf"
type = "pdf"
title = "JaIre-Workspace (1).pdf"

[[outputs]]
id = "8rd8ejkScYMRaxZhZ-GpC"
uri = "file://.local/outputs/JaIre-Workspace--1-.pptx"
type = "slides"
title = "JaIre-Workspace (1).pptx"
